"""Tests for the model-validation harness: skill metrics + observed-vs-predicted
comparison, and a solver twin experiment confirming it works on real model output.

All offline: the "observations" are generated by the model itself so no network or
gauge data is needed to exercise the harness.
"""
import numpy as np
import pytest

from general.solvers import saint_venant_1d as sv1
from rivers.validation.skill import (
    mean_bias,
    nash_sutcliffe,
    pearson_r,
    percent_bias,
    rmse,
    skill_scores,
)
from rivers.validation.compare import evaluate_series, interpolate_to


# ── skill metrics ──────────────────────────────────────────────────────────
def test_perfect_prediction_is_perfect_skill():
    obs = np.array([1.0, 2.0, 3.0, 4.0])
    assert nash_sutcliffe(obs, obs) == pytest.approx(1.0)
    assert rmse(obs, obs) == pytest.approx(0.0)
    assert mean_bias(obs, obs) == pytest.approx(0.0)
    assert pearson_r(obs, obs) == pytest.approx(1.0)


def test_nash_sutcliffe_of_mean_predictor_is_zero():
    obs = np.array([1.0, 2.0, 3.0, 4.0])
    pred = np.full(4, obs.mean())
    assert nash_sutcliffe(obs, pred) == pytest.approx(0.0)


def test_rmse_and_bias_known_values():
    obs = np.array([1.0, 2.0, 3.0])
    pred = np.array([1.0, 2.0, 5.0])  # errors 0, 0, +2
    assert rmse(obs, pred) == pytest.approx((4.0 / 3.0) ** 0.5)
    assert mean_bias(obs, pred) == pytest.approx(2.0 / 3.0)


def test_percent_bias_known_value():
    obs = np.array([2.0, 4.0, 6.0])
    pred = np.array([3.0, 5.0, 7.0])  # +1 each; sum(err)=3, sum(obs)=12
    assert percent_bias(obs, pred) == pytest.approx(25.0)


def test_skill_scores_returns_all_metrics():
    obs = np.array([1.0, 2.0, 3.0, 4.0])
    scores = skill_scores(obs, obs + 0.1)
    assert {"nse", "rmse", "bias", "percent_bias", "pearson_r", "n"} <= set(scores)
    assert scores["n"] == 4


def test_metrics_reject_mismatched_lengths():
    with pytest.raises(ValueError):
        nash_sutcliffe(np.array([1.0, 2.0]), np.array([1.0]))


# ── series alignment ───────────────────────────────────────────────────────
def test_interpolate_to_aligns_onto_target_times():
    out = interpolate_to([0.0, 10.0, 20.0], [0.0, 10.0, 20.0], [5.0, 15.0])
    assert np.allclose(out, [5.0, 15.0])


def test_evaluate_series_interpolates_predicted_onto_observed_times():
    obs_t = [0.0, 1.0, 2.0, 3.0]
    obs = [1.0, 2.0, 3.0, 4.0]
    # Predicted sampled on a finer grid but the same underlying linear signal.
    pred_t = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    pred = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
    result = evaluate_series(obs_t, obs, pred_t, pred)
    assert result["nse"] == pytest.approx(1.0)
    assert result["n"] == 4


# ── solver twin experiment ─────────────────────────────────────────────────
def test_harness_discriminates_faithful_vs_biased_solver_hydrograph():
    # Real solver output as the "observed" downstream hydrograph. The harness must
    # score a faithful prediction as perfect and a biased one as worse -- confirming
    # it works on realistic hydrograph shapes, not just toy arrays.
    nx = int(10 * 10)

    def rising_inflow(t):
        return 0.02 + 0.0004 * t  # time-varying upstream discharge

    run = sv1.run_model(10.0, 20.0, record_interval=0.5, left_inflow=rising_inflow,
                        h_init=np.full(nx, 0.02))
    times, downstream = run["times"], run["q_history"][:, -1]  # downstream discharge

    faithful = evaluate_series(times, downstream, times, downstream)
    biased = evaluate_series(times, downstream, times, downstream + 0.3 * float(np.mean(downstream)))

    assert faithful["nse"] == pytest.approx(1.0)
    assert faithful["rmse"] == pytest.approx(0.0)
    assert faithful["n"] == len(times)
    assert biased["nse"] < faithful["nse"]
    assert biased["percent_bias"] > 1.0


def test_biased_prediction_scores_below_perfect():
    obs_t = [0.0, 1.0, 2.0, 3.0]
    obs = [1.0, 2.0, 3.0, 4.0]
    pred = [1.5, 2.5, 3.5, 4.5]  # uniform +0.5 bias
    result = evaluate_series(obs_t, obs, obs_t, pred)
    assert result["nse"] < 1.0
    assert result["bias"] == pytest.approx(0.5)
