/* Parity suite: the JS solver ports must reproduce the Python solvers.
 *
 * References are generated by:  python website/build_scenarios.py --references
 * Run with:                     node --test website/test/
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { kinematicWave, saintVenant1D } from "../js/solvers.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REFERENCE_DIR = join(HERE, "reference");

const ABS_TOL = 1e-9;
const REL_TOL = 1e-8;

function assertClose(actual, expected, label) {
  const tolerance = ABS_TOL + REL_TOL * Math.abs(expected);
  assert.ok(
    Math.abs(actual - expected) <= tolerance,
    `${label}: ${actual} != ${expected} (diff ${Math.abs(actual - expected)})`,
  );
}

function assertMatrixClose(actual, expected, label) {
  assert.equal(actual.length, expected.length, `${label}: row count`);
  for (let r = 0; r < expected.length; r += 1) {
    assert.equal(actual[r].length, expected[r].length, `${label}[${r}]: column count`);
    for (let c = 0; c < expected[r].length; c += 1) {
      assertClose(actual[r][c], expected[r][c], `${label}[${r}][${c}]`);
    }
  }
}

function loadReferences() {
  return readdirSync(REFERENCE_DIR)
    .filter((name) => name.endsWith(".json"))
    .map((name) => ({ name, data: JSON.parse(readFileSync(join(REFERENCE_DIR, name), "utf-8")) }));
}

const references = loadReferences();
assert.ok(references.length >= 4, "expected at least 4 reference cases; run build_scenarios.py --references");

for (const { name, data } of references) {
  test(`parity: ${name}`, () => {
    let result;
    if (data.solver === "kinematic_wave") {
      result = kinematicWave(data.profile, data.options);
    } else if (data.solver === "saint_venant") {
      const { grid, options } = data;
      const rain = options.rain;
      result = saintVenant1D({
        x_m: grid.x_m,
        dx_m: grid.dx_m,
        slope: grid.slope,
        manning_n: grid.manning_n,
        hInit: options.hInit,
        tFinalMin: options.tFinalMin,
        recordIntervalMin: options.recordIntervalMin,
        leftInflow: options.leftInflow,
        rainfall: (x, t) => (t < rain.endMin ? rain.rate : 0.0),
      });
    } else {
      throw new Error(`unknown solver in reference: ${data.solver}`);
    }

    const expected = data.expected;
    assert.equal(result.times.length, expected.times.length, "times length");
    for (let i = 0; i < expected.times.length; i += 1) {
      assertClose(result.times[i], expected.times[i], `times[${i}]`);
    }
    assertMatrixClose(result.depth_history, expected.depth_history, "depth");
    if (expected.discharge_history) {
      assertMatrixClose(result.discharge_history, expected.discharge_history, "discharge");
    }
    assertClose(result.mass_inflow, expected.mass_inflow, "mass_inflow");
    assertClose(result.mass_source, expected.mass_source, "mass_source");
    assertClose(result.mass_outflow, expected.mass_outflow, "mass_outflow");
    if (expected.mass_floor_correction !== undefined) {
      assertClose(result.mass_floor_correction, expected.mass_floor_correction, "mass_floor_correction");
    }
  });
}
