/* Faithful JavaScript ports of the repo's 1-D solvers, for the in-browser
 * playground. Units are meters and minutes throughout (Manning n is the
 * meters-and-minutes value: conventional SI n divided by 60).
 *
 * Ported from:
 *   src/general/solvers/linear_advection.py  (kinematic wave)
 *   src/general/solvers/saint_venant_1d.py   (Saint-Venant, Rusanov fluxes)
 *
 * Parity with the Python implementations is enforced by
 * website/test/solver_parity.test.mjs against references generated by
 * website/build_scenarios.py --references. Keep the numerics in lockstep with
 * the Python sources when either changes.
 */

export const MIN_DEPTH = 1e-10; // kinematic wave depth floor
export const H_FLOOR = 1e-10;   // Saint-Venant depth floor
export const G_M_PER_MIN2 = 35316.0; // 9.81 m/s^2 in m/min^2

function zeros(n) {
  return new Float64Array(n);
}

function toArray(values) {
  return Array.from(values);
}

function maxOf(a) {
  let m = -Infinity;
  for (let i = 0; i < a.length; i += 1) if (a[i] > m) m = a[i];
  return m;
}

function minOf(a) {
  let m = Infinity;
  for (let i = 0; i < a.length; i += 1) if (a[i] < m) m = a[i];
  return m;
}

function recordMarks(tFinal, interval) {
  const count = Math.floor(tFinal / interval + 1e-9);
  const marks = [];
  for (let i = 0; i <= count; i += 1) marks.push(i * interval);
  if (marks.length === 0 || marks[marks.length - 1] < tFinal - 1e-9) {
    marks.push(tFinal);
  }
  return marks;
}

/* ── kinematic wave (linear_advection.run_model port) ─────────────────── */

export function manningFlux(h, slope, n) {
  const hh = Math.max(h, 0.0);
  return (1.0 / n) * Math.pow(hh, 5.0 / 3.0) * Math.sqrt(slope);
}

export function waveSpeed(h, slope, n) {
  const hh = Math.max(h, 0.0);
  return (5.0 / (3.0 * n)) * Math.pow(hh, 2.0 / 3.0) * Math.sqrt(slope);
}

/**
 * profile: { station_m, dx_m, slope, manning_n, initial_depth_m?, rainfall_rate_m_per_min? }
 * options: { tFinalMin, leftInflowFlux, recordIntervalMin, baseDepthM,
 *            rainfallRateMPerMin, rainfallStartMin, rainfallEndMin,
 *            rainfall (fn(station_m[], t) -> rate[] | number), cfl,
 *            onProgress (fn(fraction)) }
 */
export function kinematicWave(profile, options) {
  const {
    tFinalMin,
    leftInflowFlux,
    recordIntervalMin = 1.0,
    baseDepthM = 0.01,
    rainfallRateMPerMin = 0.0,
    rainfallStartMin = 0.0,
    rainfallEndMin = null,
    rainfall = null,
    cfl = 0.5,
    onProgress = null,
  } = options;

  const stations = Float64Array.from(profile.station_m);
  const dx = Float64Array.from(profile.dx_m);
  const slope = Float64Array.from(profile.slope);
  const manning = Float64Array.from(profile.manning_n);
  const nCells = stations.length;

  if (tFinalMin < 0) throw new Error("tFinalMin must be non-negative");
  if (recordIntervalMin <= 0) throw new Error("recordIntervalMin must be positive");
  if (leftInflowFlux < 0) throw new Error("leftInflowFlux must be non-negative");
  if (rainfallRateMPerMin < 0) throw new Error("rainfallRateMPerMin must be non-negative");
  if (!(cfl > 0 && cfl <= 1)) throw new Error("cfl must be in (0, 1]");

  let depth = zeros(nCells);
  if (profile.initial_depth_m) {
    depth.set(profile.initial_depth_m);
  } else {
    depth.fill(baseDepthM);
  }
  for (let i = 0; i < nCells; i += 1) depth[i] = Math.max(depth[i], MIN_DEPTH);
  const depthInitial = Float64Array.from(depth);

  const marks = recordMarks(tFinalMin, recordIntervalMin);
  const times = [0.0];
  const history = [toArray(depthInitial)];
  let nextMark = 1;
  let t = 0.0;

  let massInflow = 0.0;
  let massSource = 0.0;
  let massOutflow = 0.0;

  const profileRain = profile.rainfall_rate_m_per_min
    ? Float64Array.from(profile.rainfall_rate_m_per_min)
    : null;
  const dxMin = minOf(dx);

  while (t < tFinalMin - 1e-12) {
    let cMax = 0.0;
    for (let i = 0; i < nCells; i += 1) {
      const speed = waveSpeed(depth[i], slope[i], manning[i]);
      if (speed > cMax) cMax = speed;
    }
    let dt = cMax > 0 ? (cfl * dxMin) / cMax : tFinalMin - t;
    dt = Math.min(dt, tFinalMin - t);
    if (nextMark < marks.length) dt = Math.min(dt, marks[nextMark] - t);
    if (rainfallEndMin !== null && t < rainfallEndMin && rainfallEndMin < t + dt) {
      dt = rainfallEndMin - t;
    }
    if (t < rainfallStartMin && rainfallStartMin < t + dt) {
      dt = rainfallStartMin - t;
    }
    if (dt <= 1e-12) dt = Math.min(tFinalMin - t, 1e-12);

    // Upwind fluxes: left interface carries the inflow; interior interfaces the
    // upwind cell's Manning flux.
    const cellFlux = zeros(nCells);
    for (let i = 0; i < nCells; i += 1) {
      cellFlux[i] = manningFlux(depth[i], slope[i], manning[i]);
    }

    // Rainfall source (profile column + windowed uniform rate + callable).
    const source = zeros(nCells);
    if (profileRain) for (let i = 0; i < nCells; i += 1) source[i] += profileRain[i];
    const uniformActive = t >= rainfallStartMin && (rainfallEndMin === null || t < rainfallEndMin);
    if (uniformActive) for (let i = 0; i < nCells; i += 1) source[i] += rainfallRateMPerMin;
    if (rainfall) {
      const extra = rainfall(stations, t);
      if (typeof extra === "number") {
        for (let i = 0; i < nCells; i += 1) source[i] += extra;
      } else {
        for (let i = 0; i < nCells; i += 1) source[i] += extra[i];
      }
    }

    const next = zeros(nCells);
    for (let i = 0; i < nCells; i += 1) {
      const fluxIn = i === 0 ? leftInflowFlux : cellFlux[i - 1];
      let value = depth[i] - (dt / dx[i]) * (cellFlux[i] - fluxIn) + dt * source[i];
      next[i] = Math.max(value, MIN_DEPTH);
    }

    massInflow += leftInflowFlux * dt;
    let sourceMass = 0.0;
    for (let i = 0; i < nCells; i += 1) sourceMass += source[i] * dx[i];
    massSource += sourceMass * dt;
    massOutflow += cellFlux[nCells - 1] * dt;

    depth = next;
    t += dt;

    if (nextMark < marks.length && t >= marks[nextMark] - 1e-9) {
      times.push(marks[nextMark]);
      history.push(toArray(depth));
      nextMark += 1;
    }
    if (onProgress) onProgress(t / tFinalMin);
  }

  return {
    station_m: toArray(stations),
    dx_m: toArray(dx),
    times: times,
    depth_history: history,
    depth_initial: toArray(depthInitial),
    depth_final: toArray(depth),
    mass_inflow: massInflow,
    mass_source: massSource,
    mass_outflow: massOutflow,
  };
}

/* ── Saint-Venant 1-D (saint_venant_1d.run_model port) ────────────────── */

function velocity(h, q) {
  return h > H_FLOOR ? q / h : 0.0;
}

/**
 * options: { x_m, dx_m, slope, manning_n, hInit, qInit?, tFinalMin,
 *            recordIntervalMin, leftInflow (number | fn(t)),
 *            rainfall (fn(x[], t) -> rate[] | number)  [required: no default rain],
 *            cfl, onProgress }
 */
export function saintVenant1D(options) {
  const {
    x_m,
    dx_m,
    slope,
    manning_n,
    hInit,
    qInit = null,
    tFinalMin,
    recordIntervalMin = 0.05,
    leftInflow = null,
    rainfall,
    cfl = 0.5,
    onProgress = null,
  } = options;

  const x = Float64Array.from(x_m);
  const dx = Float64Array.from(dx_m);
  const bedSlope = Float64Array.from(slope);
  const roughness = Float64Array.from(manning_n);
  const n = x.length;
  const g = G_M_PER_MIN2;

  if (typeof rainfall !== "function") {
    throw new Error("saintVenant1D requires an explicit rainfall(x, t) function (use () => 0 for none)");
  }
  if (!(cfl > 0 && cfl <= 1)) throw new Error("cfl must be in (0, 1]");

  let h = Float64Array.from(hInit);
  for (let i = 0; i < n; i += 1) h[i] = Math.max(h[i], H_FLOOR);
  let q = qInit ? Float64Array.from(qInit) : zeros(n);
  for (let i = 0; i < n; i += 1) if (h[i] <= H_FLOOR) q[i] = 0.0;

  const hInitial = Float64Array.from(h);
  const qInitial = Float64Array.from(q);
  const marks = recordMarks(tFinalMin, recordIntervalMin);
  const times = [0.0];
  const hHistory = [toArray(h)];
  const qHistory = [toArray(q)];
  let nextMark = 1;
  let t = 0.0;

  let massInflow = 0.0;
  let massSource = 0.0;
  let massOutflow = 0.0;
  let massFloor = 0.0;

  const inflowAt = (time) => {
    const value = typeof leftInflow === "function" ? leftInflow(time) : leftInflow;
    const number = value === null || value === undefined ? 0.0 : Number(value);
    if (!Number.isFinite(number) || number < 0) {
      throw new Error("leftInflow must be a finite, non-negative discharge");
    }
    return number;
  };

  // Extended (ghost) arrays reused across steps.
  const hExt = zeros(n + 2);
  const qExt = zeros(n + 2);
  const fluxH = zeros(n + 1);
  const fluxQ = zeros(n + 1);
  const speed = zeros(n + 1);

  while (t < tFinalMin - 1e-12) {
    const inflow = inflowAt(t);

    // Ghost cells: equal depths; q mirrored about the requested inflow on the
    // left, zero-gradient on the right.
    hExt[0] = h[0];
    qExt[0] = 2.0 * inflow - q[0];
    for (let i = 0; i < n; i += 1) {
      hExt[i + 1] = h[i];
      qExt[i + 1] = q[i];
    }
    hExt[n + 1] = h[n - 1];
    qExt[n + 1] = q[n - 1];

    for (let f = 0; f <= n; f += 1) {
      const hL = hExt[f];
      const qL = qExt[f];
      const hR = hExt[f + 1];
      const qR = qExt[f + 1];
      const uL = velocity(hL, qL);
      const uR = velocity(hR, qR);
      const fluxHL = qL;
      const fluxHR = qR;
      const fluxQL = qL * uL + 0.5 * g * hL * hL;
      const fluxQR = qR * uR + 0.5 * g * hR * hR;
      const sL = Math.abs(uL) + Math.sqrt(g * hL);
      const sR = Math.abs(uR) + Math.sqrt(g * hR);
      const alpha = Math.max(sL, sR);
      fluxH[f] = 0.5 * (fluxHL + fluxHR) - 0.5 * alpha * (hR - hL);
      fluxQ[f] = 0.5 * (fluxQL + fluxQR) - 0.5 * alpha * (qR - qL);
      speed[f] = alpha;
    }

    // dt from per-cell speeds (max of the two adjacent interface speeds).
    let dt = Infinity;
    let anyMoving = false;
    for (let i = 0; i < n; i += 1) {
      const cellSpeed = Math.max(speed[i], speed[i + 1]);
      if (cellSpeed > 1e-12) {
        anyMoving = true;
        const candidate = dx[i] / cellSpeed;
        if (candidate < dt) dt = candidate;
      }
    }
    dt = anyMoving ? cfl * dt : tFinalMin - t;
    dt = Math.min(dt, tFinalMin - t);

    const hPrev = Float64Array.from(h);
    const qPrev = Float64Array.from(q);

    const rain = rainfall(x, t);
    const source = zeros(n);
    if (typeof rain === "number") {
      source.fill(rain);
    } else {
      source.set(rain);
    }

    const hNew = zeros(n);
    const qNew = zeros(n);
    for (let i = 0; i < n; i += 1) {
      let value = h[i] - (dt / dx[i]) * (fluxH[i + 1] - fluxH[i]) + dt * source[i];
      const floorAdd = Math.max(H_FLOOR - value, 0.0);
      massFloor += floorAdd * dx[i];
      hNew[i] = Math.max(value, H_FLOOR);
      qNew[i] = q[i] - (dt / dx[i]) * (fluxQ[i + 1] - fluxQ[i]);
    }
    for (let i = 0; i < n; i += 1) {
      const u = velocity(hNew[i], qNew[i]);
      const friction = roughness[i] * roughness[i] * Math.abs(u) / Math.pow(hNew[i], 4.0 / 3.0);
      qNew[i] = (qNew[i] + dt * g * hNew[i] * bedSlope[i]) / (1.0 + dt * g * friction);
      if (hNew[i] <= H_FLOOR) qNew[i] = 0.0;
    }

    massInflow += fluxH[0] * dt;
    massOutflow += fluxH[n] * dt;
    let sourceMass = 0.0;
    for (let i = 0; i < n; i += 1) sourceMass += source[i] * dx[i];
    massSource += sourceMass * dt;

    const tNext = t + dt;
    while (nextMark < marks.length && marks[nextMark] <= tNext + 1e-10) {
      const mark = marks[nextMark];
      let fraction = dt === 0 ? 1.0 : (mark - t) / dt;
      fraction = Math.min(Math.max(fraction, 0.0), 1.0);
      const hRow = new Array(n);
      const qRow = new Array(n);
      for (let i = 0; i < n; i += 1) {
        hRow[i] = hPrev[i] + fraction * (hNew[i] - hPrev[i]);
        qRow[i] = qPrev[i] + fraction * (qNew[i] - qPrev[i]);
      }
      times.push(mark);
      hHistory.push(hRow);
      qHistory.push(qRow);
      nextMark += 1;
    }

    h = hNew;
    q = qNew;
    t = tNext;
    if (onProgress) onProgress(t / tFinalMin);
  }

  return {
    station_m: toArray(x),
    dx_m: toArray(dx),
    times: times,
    depth_history: hHistory,
    discharge_history: qHistory,
    depth_initial: toArray(hInitial),
    depth_final: toArray(h),
    discharge_initial: toArray(qInitial),
    discharge_final: toArray(q),
    mass_inflow: massInflow,
    mass_source: massSource,
    mass_outflow: massOutflow,
    mass_floor_correction: massFloor,
  };
}
