/* Faithful JavaScript port of the repo's verified 2-D shallow-water solver,
 * for the in-browser playground and the 2-D atlas regions.
 *
 * Ported from src/general/solvers/saint_venant_2d.py: Rusanov fluxes with
 * hydrostatic reconstruction (well-balanced over non-flat bed) and a
 * conservative donor-based draining limiter (positivity without a mass-adding
 * depth floor).
 *
 * Fields are flat Float64Arrays in row-major order, index = i * ny + j, where
 * i indexes downstream (x) and j indexes across the channel (y). Units are
 * meters and minutes (Manning n is the SI value divided by 60).
 *
 * Parity with the Python implementation is enforced by
 * website/test/solver_parity.test.mjs against references generated by
 * website/build_scenarios.py --references. Keep the numerics in lockstep.
 *
 * Deliberately NOT ported: the module-level r(t) rainfall default (0.1 m/min,
 * a verification convenience) and the momentum_source hook (manufactured-
 * solution verification only). Callers must pass rainfall explicitly.
 */

export const G_M_PER_MIN2 = 35316.0;
export const DRY_TOL = 1e-10;
export const POSITIVITY_TOL = 1e-12;
export const CFL_2D = 0.45;

function zeros(n) {
  return new Float64Array(n);
}

function recordMarks(tFinal, interval) {
  const count = Math.floor(tFinal / interval + 1e-9);
  const marks = [];
  for (let k = 0; k <= count; k += 1) marks.push(k * interval);
  if (marks.length === 0 || marks[marks.length - 1] < tFinal - 1e-9) marks.push(tFinal);
  return marks;
}

function velocity(h, momentum) {
  return h > DRY_TOL ? momentum / h : 0.0;
}

function waveSpeed(h, momentum) {
  return Math.abs(velocity(h, momentum)) + Math.sqrt(G_M_PER_MIN2 * Math.max(h, 0.0));
}

/** Expand a scalar / longitudinal / full field to a flat nx*ny Float64Array. */
export function field2d(value, fallback, nx, ny, name) {
  const out = zeros(nx * ny);
  const source = value === null || value === undefined ? fallback : value;
  if (typeof source === "number") {
    if (!Number.isFinite(source)) throw new Error(`${name} must be finite`);
    out.fill(source);
    return out;
  }
  const flat = ArrayBuffer.isView(source) ? source : Array.from(source);
  if (flat.length === nx * ny) {
    for (let k = 0; k < out.length; k += 1) out[k] = flat[k];
  } else if (flat.length === nx) {
    // Longitudinal profile broadcast across y.
    for (let i = 0; i < nx; i += 1) for (let j = 0; j < ny; j += 1) out[i * ny + j] = flat[i];
  } else {
    throw new Error(`${name} must be scalar, length ${nx} (longitudinal), or length ${nx * ny}`);
  }
  for (let k = 0; k < out.length; k += 1) {
    if (!Number.isFinite(out[k])) throw new Error(`${name} must contain finite values`);
  }
  return out;
}

/** Cell centres and widths for a uniform axis of `count` cells over `length`. */
export function uniformAxis(length, count) {
  const step = length / count;
  const centres = new Float64Array(count);
  const widths = new Float64Array(count);
  for (let k = 0; k < count; k += 1) {
    // np.linspace(step/2, length - step/2, count)
    centres[k] = count === 1 ? step / 2 : step / 2 + (k * (length - step)) / (count - 1);
    widths[k] = step;
  }
  return { centres, widths };
}

function inflowValues(leftInflow, time, ny) {
  const raw = typeof leftInflow === "function" ? leftInflow(time) : leftInflow;
  const out = zeros(ny);
  if (typeof raw === "number") {
    out.fill(raw);
  } else {
    if (raw.length !== ny) throw new Error(`left_inflow must be scalar or length ${ny}`);
    for (let j = 0; j < ny; j += 1) out[j] = raw[j];
  }
  for (let j = 0; j < ny; j += 1) {
    if (!Number.isFinite(out[j]) || out[j] < 0) {
      throw new Error("left_inflow must be finite and non-negative");
    }
  }
  return out;
}

/**
 * options: {
 *   nx, ny, x_m, y_m, dx_m, dy_m,            // grid (centres + widths)
 *   bedElevationM,                            // required: flat nx*ny bed datum
 *   manningN,                                 // scalar or flat field
 *   hInit, huInit, hvInit,
 *   tFinalMin, recordIntervalMin,
 *   leftInflow,                               // number | Float64Array(ny) | fn(t)
 *   rainfall,                                 // fn(t) -> number | flat field  [required]
 *   cfl, boundaryX ("inflow_outflow"|"periodic"), boundaryY ("wall"|"periodic"),
 *   maxSteps                                  // abort guard for the browser
 * }
 */
export function saintVenant2D(options) {
  const {
    x_m,
    y_m,
    dx_m,
    dy_m,
    bedElevationM,
    manningN = 0.05 / 60.0,
    hInit = 0.01,
    huInit = 0.0,
    hvInit = 0.0,
    tFinalMin,
    recordIntervalMin = 1.0,
    leftInflow = 0.0,
    rainfall,
    cfl = CFL_2D,
    boundaryX = "inflow_outflow",
    boundaryY = "wall",
    maxSteps = Infinity,
  } = options;

  if (!(tFinalMin >= 0) || !Number.isFinite(tFinalMin)) {
    throw new Error("tFinalMin must be finite and non-negative");
  }
  if (!(recordIntervalMin > 0)) throw new Error("recordIntervalMin must be positive");
  if (!(cfl > 0 && cfl <= 0.5)) throw new Error("2-D cfl must be in (0, 0.5]");
  if (boundaryX !== "inflow_outflow" && boundaryX !== "periodic") {
    throw new Error("boundaryX must be 'inflow_outflow' or 'periodic'");
  }
  if (boundaryY !== "wall" && boundaryY !== "periodic") {
    throw new Error("boundaryY must be 'wall' or 'periodic'");
  }
  if (typeof rainfall !== "function") {
    throw new Error("saintVenant2D requires an explicit rainfall(t) function (use () => 0 for none)");
  }

  const x = Float64Array.from(x_m);
  const y = Float64Array.from(y_m);
  const dx = Float64Array.from(dx_m);
  const dy = Float64Array.from(dy_m);
  const nx = x.length;
  const ny = y.length;
  const size = nx * ny;
  const g = G_M_PER_MIN2;

  const bed = field2d(bedElevationM, 0.0, nx, ny, "bed_elevation_m");
  const roughness = field2d(manningN, 0.05 / 60.0, nx, ny, "manning_n");
  for (let k = 0; k < size; k += 1) {
    if (roughness[k] < 0) throw new Error("manning_n cannot be negative");
  }

  let h = field2d(hInit, 0.01, nx, ny, "h_init");
  let hu = field2d(huInit, 0.0, nx, ny, "hu_init");
  let hv = field2d(hvInit, 0.0, nx, ny, "hv_init");
  for (let k = 0; k < size; k += 1) {
    if (h[k] < 0) throw new Error("h_init cannot contain negative depths");
    if (h[k] <= DRY_TOL) {
      hu[k] = 0.0;
      hv[k] = 0.0;
    }
  }

  const hInitial = Float64Array.from(h);
  const marks = recordMarks(tFinalMin, recordIntervalMin);
  const times = [0.0];
  const hHistory = [Float64Array.from(h)];
  const huHistory = [Float64Array.from(hu)];
  const hvHistory = [Float64Array.from(hv)];
  let nextMark = 1;

  let massInflow = 0.0;
  let massOutflow = 0.0;
  let massSource = 0.0;
  let massFloorCorrection = 0.0;
  let t = 0.0;
  let steps = 0;

  // ── scratch buffers (allocated once, reused each step) ────────────────
  const xFaces = (nx + 1) * ny;
  const yFaces = nx * (ny + 1);
  const fh = zeros(xFaces);
  const fhu = zeros(xFaces);
  const fhv = zeros(xFaces);
  const corrXLeft = zeros(xFaces);
  const corrXRight = zeros(xFaces);
  const gh = zeros(yFaces);
  const ghu = zeros(yFaces);
  const ghv = zeros(yFaces);
  const corrYBottom = zeros(yFaces);
  const corrYTop = zeros(yFaces);
  const theta = zeros(size);
  const source = zeros(size);
  const hNew = zeros(size);
  const huStar = zeros(size);
  const hvStar = zeros(size);

  // Ghost accessors mirroring _extend_x / _extend_y. Extended x index e runs
  // 0..nx+1 with e = 0 the left ghost column and e = nx+1 the right ghost.
  const extX = (e) => (boundaryX === "periodic"
    ? (e === 0 ? nx - 1 : e === nx + 1 ? 0 : e - 1)
    : (e === 0 ? 0 : e === nx + 1 ? nx - 1 : e - 1));
  const extY = (e) => (boundaryY === "periodic"
    ? (e === 0 ? ny - 1 : e === ny + 1 ? 0 : e - 1)
    : (e === 0 ? 0 : e === ny + 1 ? ny - 1 : e - 1));

  while (t < tFinalMin - 1e-14) {
    steps += 1;
    if (steps > maxSteps) {
      throw new Error(`2-D run exceeded ${maxSteps} time steps at t=${t.toFixed(3)} min`);
    }

    // ── time step from the spectral radius ──────────────────────────────
    let maxRate = 0.0;
    for (let i = 0; i < nx; i += 1) {
      for (let j = 0; j < ny; j += 1) {
        const k = i * ny + j;
        const rate = waveSpeed(h[k], hu[k]) / dx[i] + waveSpeed(h[k], hv[k]) / dy[j];
        if (rate > maxRate) maxRate = rate;
      }
    }
    let dt = maxRate <= 1e-14 ? tFinalMin - t : cfl / maxRate;
    dt = Math.min(dt, tFinalMin - t);
    if (nextMark < marks.length) dt = Math.min(dt, marks[nextMark] - t);
    if (!(dt > 0) || !Number.isFinite(dt)) {
      throw new Error(`Invalid time step ${dt} at t=${t}`);
    }

    const inflow = inflowValues(leftInflow, t, ny);

    // ── Rusanov fluxes in x, with hydrostatic reconstruction ────────────
    for (let f = 0; f <= nx; f += 1) {
      const li = extX(f);
      const ri = extX(f + 1);
      // Left ghost carries the prescribed unit discharge (mirrored about it);
      // the right ghost is zero-gradient, which extX already provides.
      const leftGhost = boundaryX !== "periodic" && f === 0;
      for (let j = 0; j < ny; j += 1) {
        const lk = li * ny + j;
        const rk = ri * ny + j;
        const hL = h[lk];
        const hR = h[rk];
        const huL = leftGhost ? 2.0 * inflow[j] - hu[lk] : hu[lk];
        const huR = hu[rk];
        const hvL = hv[lk];
        const hvR = hv[rk];
        const bedL = bed[lk];
        const bedR = bed[rk];

        const faceBed = Math.max(bedL, bedR);
        const depthL = Math.max(0.0, hL + bedL - faceBed);
        const depthR = Math.max(0.0, hR + bedR - faceBed);
        const scaleL = hL > DRY_TOL ? depthL / hL : 0.0;
        const scaleR = hR > DRY_TOL ? depthR / hR : 0.0;
        const hsL = depthL;
        const husL = huL * scaleL;
        const hvsL = hvL * scaleL;
        const hsR = depthR;
        const husR = huR * scaleR;
        const hvsR = hvR * scaleR;

        const uL = velocity(hsL, husL);
        const uR = velocity(hsR, husR);
        const alpha = Math.max(waveSpeed(hsL, husL), waveSpeed(hsR, husR));
        const fk = f * ny + j;
        fh[fk] = 0.5 * (husL + husR) - 0.5 * alpha * (hsR - hsL);
        fhu[fk] = 0.5 * ((husL * uL + 0.5 * g * hsL * hsL) + (husR * uR + 0.5 * g * hsR * hsR))
          - 0.5 * alpha * (husR - husL);
        fhv[fk] = 0.5 * (hvsL * uL + hvsR * uR) - 0.5 * alpha * (hvsR - hvsL);
        corrXLeft[fk] = 0.5 * g * (hL * hL - hsL * hsL);
        corrXRight[fk] = 0.5 * g * (hR * hR - hsR * hsR);
      }
    }

    // ── Rusanov fluxes in y ─────────────────────────────────────────────
    for (let i = 0; i < nx; i += 1) {
      for (let f = 0; f <= ny; f += 1) {
        const bj = extY(f);
        const tj = extY(f + 1);
        const bottomGhost = boundaryY !== "periodic" && f === 0;
        const topGhost = boundaryY !== "periodic" && f === ny;
        const bk = i * ny + bj;
        const tk = i * ny + tj;
        const hB = h[bk];
        const hT = h[tk];
        const huB = hu[bk];
        const huT = hu[tk];
        // Wall: reflect the lateral momentum in the ghost cells.
        const hvB = bottomGhost ? -hv[bk] : hv[bk];
        const hvT = topGhost ? -hv[tk] : hv[tk];
        const bedB = bed[bk];
        const bedT = bed[tk];

        const faceBed = Math.max(bedB, bedT);
        const depthB = Math.max(0.0, hB + bedB - faceBed);
        const depthT = Math.max(0.0, hT + bedT - faceBed);
        const scaleB = hB > DRY_TOL ? depthB / hB : 0.0;
        const scaleT = hT > DRY_TOL ? depthT / hT : 0.0;
        const hsB = depthB;
        const husB = huB * scaleB;
        const hvsB = hvB * scaleB;
        const hsT = depthT;
        const husT = huT * scaleT;
        const hvsT = hvT * scaleT;

        const vB = velocity(hsB, hvsB);
        const vT = velocity(hsT, hvsT);
        const alpha = Math.max(waveSpeed(hsB, hvsB), waveSpeed(hsT, hvsT));
        const fk = i * (ny + 1) + f;
        gh[fk] = 0.5 * (hvsB + hvsT) - 0.5 * alpha * (hsT - hsB);
        ghu[fk] = 0.5 * (husB * vB + husT * vT) - 0.5 * alpha * (husT - husB);
        ghv[fk] = 0.5 * ((hvsB * vB + 0.5 * g * hsB * hsB) + (hvsT * vT + 0.5 * g * hsT * hsT))
          - 0.5 * alpha * (hvsT - hvsB);
        corrYBottom[fk] = 0.5 * g * (hB * hB - hsB * hsB);
        corrYTop[fk] = 0.5 * g * (hT * hT - hsT * hsT);
      }
    }

    // ── rainfall source ─────────────────────────────────────────────────
    const rain = rainfall(t);
    if (typeof rain === "number") {
      if (!Number.isFinite(rain)) throw new Error("rainfall must be finite");
      source.fill(rain);
    } else {
      for (let k = 0; k < size; k += 1) source[k] = rain[k];
    }
    for (let k = 0; k < size; k += 1) {
      if (source[k] < 0) throw new Error("rainfall cannot be negative");
    }

    // ── conservative draining limiter ───────────────────────────────────
    for (let i = 0; i < nx; i += 1) {
      for (let j = 0; j < ny; j += 1) {
        const k = i * ny + j;
        const outgoing = Math.max(fh[(i + 1) * ny + j], 0.0) * dy[j]
          + Math.max(-fh[i * ny + j], 0.0) * dy[j]
          + Math.max(gh[i * (ny + 1) + j + 1], 0.0) * dx[i]
          + Math.max(-gh[i * (ny + 1) + j], 0.0) * dx[i];
        const available = (h[k] + dt * source[k]) * (dx[i] * dy[j]);
        let value = 1.0;
        if (dt * outgoing > available) value = available / (dt * outgoing);
        theta[k] = Math.min(Math.max(value, 0.0), 1.0);
      }
    }
    // Donor-cell scaling: an outgoing face flux is limited by the cell it
    // drains, boundary faces by 1 (or the wrapped cell when periodic).
    for (let f = 0; f <= nx; f += 1) {
      for (let j = 0; j < ny; j += 1) {
        const fk = f * ny + j;
        let factor;
        if (fh[fk] >= 0.0) {
          factor = boundaryX === "periodic"
            ? theta[(f === 0 ? nx - 1 : f - 1) * ny + j]
            : (f === 0 ? 1.0 : theta[(f - 1) * ny + j]);
        } else {
          factor = boundaryX === "periodic"
            ? theta[(f === nx ? 0 : f) * ny + j]
            : (f === nx ? 1.0 : theta[f * ny + j]);
        }
        fh[fk] *= factor;
        fhu[fk] *= factor;
        fhv[fk] *= factor;
      }
    }
    for (let i = 0; i < nx; i += 1) {
      for (let f = 0; f <= ny; f += 1) {
        const fk = i * (ny + 1) + f;
        let factor;
        if (gh[fk] >= 0.0) {
          factor = boundaryY === "periodic"
            ? theta[i * ny + (f === 0 ? ny - 1 : f - 1)]
            : (f === 0 ? 1.0 : theta[i * ny + f - 1]);
        } else {
          factor = boundaryY === "periodic"
            ? theta[i * ny + (f === ny ? 0 : f)]
            : (f === ny ? 1.0 : theta[i * ny + f]);
        }
        gh[fk] *= factor;
        ghu[fk] *= factor;
        ghv[fk] *= factor;
      }
    }

    // ── conservative update ─────────────────────────────────────────────
    for (let i = 0; i < nx; i += 1) {
      for (let j = 0; j < ny; j += 1) {
        const k = i * ny + j;
        const xr = (i + 1) * ny + j;
        const xl = i * ny + j;
        const yt = i * (ny + 1) + j + 1;
        const yb = i * (ny + 1) + j;
        hNew[k] = h[k] - dt * ((fh[xr] - fh[xl]) / dx[i] + (gh[yt] - gh[yb]) / dy[j])
          + dt * source[k];
        huStar[k] = hu[k] - dt * (
          ((fhu[xr] + corrXLeft[xr]) - (fhu[xl] + corrXRight[xl])) / dx[i]
          + (ghu[yt] - ghu[yb]) / dy[j]
        );
        hvStar[k] = hv[k] - dt * (
          (fhv[xr] - fhv[xl]) / dx[i]
          + ((ghv[yt] + corrYBottom[yt]) - (ghv[yb] + corrYTop[yb])) / dy[j]
        );
      }
    }

    // ── positivity check (must not trigger: the limiter guarantees it) ───
    let negativeVolume = 0.0;
    let totalVolume = 0.0;
    for (let i = 0; i < nx; i += 1) {
      for (let j = 0; j < ny; j += 1) {
        const k = i * ny + j;
        const area = dx[i] * dy[j];
        if (hNew[k] < 0) negativeVolume -= hNew[k] * area;
        totalVolume += h[k] * area;
      }
    }
    const scale = Math.max(1.0, totalVolume);
    if (negativeVolume > POSITIVITY_TOL * scale) {
      throw new Error(
        `Positivity limiter failed at t=${t + dt}: negative volume=${negativeVolume.toExponential(6)}`,
      );
    }
    massFloorCorrection += negativeVolume;
    for (let k = 0; k < size; k += 1) if (hNew[k] < 0) hNew[k] = 0.0;

    // ── semi-implicit Manning friction ──────────────────────────────────
    for (let k = 0; k < size; k += 1) {
      const depth = hNew[k];
      const wet = depth > DRY_TOL;
      if (!wet) {
        hu[k] = 0.0;
        hv[k] = 0.0;
        h[k] = depth;
        continue;
      }
      const u = velocity(depth, huStar[k]);
      const v = velocity(depth, hvStar[k]);
      const speed = Math.sqrt(u * u + v * v);
      const friction = (roughness[k] * roughness[k] * speed) / Math.pow(depth, 4.0 / 3.0);
      const denominator = 1.0 + dt * g * friction;
      hu[k] = huStar[k] / denominator;
      hv[k] = hvStar[k] / denominator;
      h[k] = depth;
    }
    for (let k = 0; k < size; k += 1) {
      if (!Number.isFinite(h[k]) || !Number.isFinite(hu[k]) || !Number.isFinite(hv[k])) {
        throw new Error(`state became non-finite at t=${t + dt} min`);
      }
    }

    // ── mass ledger ─────────────────────────────────────────────────────
    if (boundaryX === "inflow_outflow") {
      let inSum = 0.0;
      let outSum = 0.0;
      for (let j = 0; j < ny; j += 1) {
        inSum += fh[j] * dy[j];
        outSum += fh[nx * ny + j] * dy[j];
      }
      massInflow += inSum * dt;
      massOutflow += outSum * dt;
    }
    let sourceSum = 0.0;
    for (let i = 0; i < nx; i += 1) {
      for (let j = 0; j < ny; j += 1) sourceSum += source[i * ny + j] * dx[i] * dy[j];
    }
    massSource += sourceSum * dt;

    t += dt;
    if (nextMark < marks.length && t >= marks[nextMark] - 1e-12) {
      times.push(marks[nextMark]);
      hHistory.push(Float64Array.from(h));
      huHistory.push(Float64Array.from(hu));
      hvHistory.push(Float64Array.from(hv));
      nextMark += 1;
    }
  }

  return {
    nx,
    ny,
    x_m: Array.from(x),
    y_m: Array.from(y),
    dx_m: Array.from(dx),
    dy_m: Array.from(dy),
    bed_elevation_m: bed,
    times,
    depth_history: hHistory,
    discharge_x_history: huHistory,
    discharge_y_history: hvHistory,
    depth_initial: hInitial,
    depth_final: Float64Array.from(h),
    discharge_x_final: Float64Array.from(hu),
    discharge_y_final: Float64Array.from(hv),
    mass_inflow: massInflow,
    mass_source: massSource,
    mass_outflow: massOutflow,
    mass_floor_correction: massFloorCorrection,
    steps,
  };
}

/* ── compound-channel helpers shared by the atlas builder and playground ── */

/**
 * Bed datum for a straight compound channel: a main channel of half-width
 * `halfWidthM` flanked by benches rising `bankHeightM` over `transitionM`,
 * on a constant downstream slope.
 */
export function compoundChannelBed({ x, y, slopeX, bankHeightM, halfWidthM, transitionM }) {
  const nx = x.length;
  const ny = y.length;
  const bed = zeros(nx * ny);
  const centre = 0.5 * (y[0] + y[ny - 1]);
  const lateral = new Float64Array(ny);
  for (let j = 0; j < ny; j += 1) {
    const offset = (Math.abs(y[j] - centre) - halfWidthM) / transitionM;
    lateral[j] = bankHeightM * Math.min(Math.max(offset, 0.0), 1.0);
  }
  for (let i = 0; i < nx; i += 1) {
    const along = -slopeX * x[i];
    for (let j = 0; j < ny; j += 1) bed[i * ny + j] = along + lateral[j];
  }
  return bed;
}

/** Normal-flow initial state: uniform channel depth, dry benches. */
export function normalFlowState({ x, y, bed, slopeX, channelDepthM, manningN }) {
  const nx = x.length;
  const ny = y.length;
  const h = zeros(nx * ny);
  const hu = zeros(nx * ny);
  const inletDischarge = new Float64Array(ny);
  for (let i = 0; i < nx; i += 1) {
    const surface = -slopeX * x[i] + channelDepthM;
    for (let j = 0; j < ny; j += 1) {
      const k = i * ny + j;
      const depth = Math.max(surface - bed[k], 0.0);
      h[k] = depth;
      hu[k] = (1.0 / manningN) * Math.pow(depth, 5.0 / 3.0) * Math.sqrt(slopeX);
      if (i === 0) inletDischarge[j] = hu[k];
    }
  }
  return { h, hu, inletDischarge };
}
