/* Validation tab: the Saint-Venant 2-D solver against real observed events,
 * across eight rivers.
 *
 * Source data: website/data/validation.json, generated by
 * `python website/build_scenarios.py` from the tracked outputs of
 * src/rivers/validation/{run_suite,run_case_2d}.py. Nothing here recomputes
 * anything from the solver.
 *
 * Deliberate framing: this is an uncalibrated 2-D screening, not a certification.
 * Two honesty devices run throughout:
 *   - Every Nash-Sutcliffe score sits next to the event's observed variability
 *     (CoV). NSE's denominator is the observed variance, so on a nearly-steady
 *     river it turns unreliable; the page says so rather than letting a negative
 *     number stand unexplained.
 *   - The per-event diagnosis includes a volume-only counterfactual that uses
 *     held-out downstream volume as an oracle. Its guard text — "not a permitted
 *     correction" — is shown verbatim, never dropped.
 */

import {
  divergingBars,
  formatNumber,
  multiSeriesChart,
  scatterChart,
} from "./charts.js";

const KIND = {
  multi_event_river: "multi-event",
  independent_river: "independent river",
  predeclared_transfer_test: "predeclared test",
};

const state = { data: null, river: null, event: null };

function showError(message) {
  const card = document.getElementById("validation-error");
  card.hidden = false;
  card.textContent = message;
}

function humanStatus(id) {
  return String(id || "").replace(/_/g, " ");
}

function allEvents() {
  return state.data.rivers.flatMap((river) =>
    river.events.map((event) => ({ river, event })));
}

function shortRiver(river) {
  return river.name.split("—")[0].trim().replace(" River", "");
}

function renderMetricNote() {
  const note = state.data.metric_note;
  const host = document.getElementById("metric-note");
  host.innerHTML = `<strong></strong><p></p>`;
  host.querySelector("strong").textContent = note.title;
  host.querySelector("p").textContent = note.text;
}

function renderRiverChoice() {
  const host = document.getElementById("river-choice");
  host.innerHTML = "";
  for (const river of state.data.rivers) {
    const worst = Math.min(...river.events.map((e) => e.scores.nse));
    const best = Math.max(...river.events.map((e) => e.scores.nse));
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `<span class="name"></span>
      <span class="meta"><span class="chip-status"></span><span class="chip-score mono"></span></span>`;
    button.querySelector(".name").textContent = shortRiver(river);
    const chip = button.querySelector(".chip-status");
    chip.textContent = KIND[river.kind] || river.kind;
    chip.classList.add(river.kind === "predeclared_transfer_test" ? "base" : "oos");
    button.querySelector(".chip-score").textContent =
      river.events.length > 1 ? `NSE ${formatNumber(worst, 2)}–${formatNumber(best, 2)}`
        : `NSE ${formatNumber(best, 2)}`;
    button.onclick = () => selectRiver(river);
    host.appendChild(button);
  }
}

function selectRiver(river) {
  state.river = river;
  document.querySelectorAll("#river-choice button").forEach((b, i) =>
    b.setAttribute("aria-pressed", state.data.rivers[i] === river ? "true" : "false"));

  const host = document.getElementById("event-choice-val");
  host.innerHTML = "";
  for (const event of river.events) {
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `<span class="name"></span>
      <span class="meta"><span class="chip-score mono"></span><span class="chip-cov mono"></span></span>`;
    button.querySelector(".name").textContent = event.date;
    button.querySelector(".chip-score").textContent = `NSE ${formatNumber(event.scores.nse, 2)}`;
    const cov = button.querySelector(".chip-cov");
    cov.textContent = `CoV ${formatNumber(event.cov_percent, 0)}%`;
    if (event.low_variability) cov.classList.add("low");
    button.onclick = () => selectEvent(river, event);
    host.appendChild(button);
  }
  renderLimits(river);
  selectEvent(river, river.events[0]);
}

function selectEvent(river, event) {
  state.event = event;
  document.querySelectorAll("#event-choice-val button").forEach((b, i) =>
    b.setAttribute("aria-pressed", river.events[i] === event ? "true" : "false"));

  document.getElementById("case-purpose").textContent =
    `${event.name} — ${humanStatus(event.status)}.` + (event.purpose ? ` ${event.purpose}` : "");

  const preNote = document.getElementById("predeclared-note");
  if (event.predeclared && river.predeclared_policy) {
    const policy = river.predeclared_policy;
    preNote.hidden = false;
    preNote.innerHTML =
      `<div class="policy-head"><h2>Predeclared before any data was seen</h2></div>
       <p class="policy-line">${policy.event_basis || ""} ${policy.first_run_policy || ""}</p>`;
  } else {
    preNote.hidden = true;
  }

  renderReadouts(event);

  document.getElementById("val-hydro-title").textContent =
    `Modelled against observed discharge — ${shortRiver(river)}, ${event.date}`;
  multiSeriesChart(document.getElementById("val-hydrograph"), {
    times: event.times_min,
    unit: "discharge (m³/min)",
    series: [
      { label: "observed at the gauge", values: event.observed_m3_per_min, color: "#0b7285", width: 2.2 },
      { label: "modelled (2-D)", values: event.predicted_m3_per_min, color: "#c0392b", width: 2, dash: "6 4" },
    ],
  });
  scatterChart(document.getElementById("val-scatter"), {
    observed: event.observed_m3_per_min,
    predicted: event.predicted_m3_per_min,
    unit: "(m³/min)",
  });
  renderReadAcross(event);
  renderSkillBars(event);
  renderDiagnosis(event);
  renderTerrain(event);
}

function renderReadouts(event) {
  const s = event.scores;
  const nseSub = event.low_variability
    ? `unreliable here — flow varied only ${formatNumber(event.cov_percent, 1)}%`
    : s.nse < 0 ? "worse than predicting the mean" : "1 perfect · 0 = the mean · <0 worse";
  document.getElementById("case-scores").innerHTML = [
    { k: "Nash–Sutcliffe", v: formatNumber(s.nse, 2), sub: nseSub, warn: event.low_variability },
    { k: "Observed variability", v: `${formatNumber(event.cov_percent, 1)}%`,
      sub: event.low_variability ? "nearly steady — prefer r and bias" : "coefficient of variation" },
    { k: "Correlation", v: formatNumber(s.pearson_r, 3), sub: "how well the shape matches" },
    { k: "Bias", v: `${formatNumber(s.percent_bias, 1)}%`,
      sub: `${formatNumber(Math.abs(s.bias), 0)} m³/min too ${s.bias < 0 ? "little" : "much"}` },
  ].map((r) => `<div class="readout${r.warn ? " warn" : ""}"><span class="k">${r.k}</span>` +
    `<span class="v">${r.v}</span><span class="s">${r.sub}</span></div>`).join("");
}

function renderReadAcross(event) {
  const s = event.scores;
  const host = document.getElementById("val-readacross");
  if (event.low_variability) {
    host.innerHTML =
      `<h3>What that shows</h3>
       <p class="readacross-line">This day's flow barely moved — it varied only
       <b>${formatNumber(event.cov_percent, 1)}%</b> around its mean. The 2-D model reproduces that
       near-constant level to within <b>${formatNumber(Math.abs(s.percent_bias), 1)}%</b>
       (correlation ${formatNumber(s.pearson_r, 2)}).</p>
       <p class="readacross-line">The Nash–Sutcliffe score of <b>${formatNumber(s.nse, 2)}</b> looks
       alarming only because NSE divides by the observed variance, which is tiny here. On a nearly
       steady river it is the wrong lens; the ~${formatNumber(Math.abs(s.percent_bias), 0)}% magnitude
       match is the honest read.</p>`;
    return;
  }
  const over = s.percent_bias > 0;
  const below = event.observed_m3_per_min.filter((o, i) => event.predicted_m3_per_min[i] < o).length;
  const belowShare = (below / event.observed_m3_per_min.length) * 100;
  const onSide = over ? 100 - belowShare : belowShare;
  host.innerHTML =
    `<h3>What that shows</h3>
     <p class="readacross-line">The model tracks the <b>shape</b> of the day
     ${s.pearson_r >= 0.9 ? "closely" : "reasonably"} — correlation
     ${formatNumber(s.pearson_r, 3)} — but runs <b>${over ? "above" : "below"}</b> the gauge by
     <b>${formatNumber(Math.abs(s.percent_bias), 1)}%</b> on average
     (${formatNumber(onSide, 0)}% of the ${s.n} readings on that side).</p>
     <p class="readacross-line">The diagnosis panel below separates that into a level error and a
     timing error, on this reach's declared 2-D terrain with no parameter fitted to the gauge.</p>`;
}

function renderSkillBars(current) {
  const events = allEvents();
  divergingBars(document.getElementById("val-skill"),
    events.map(({ river, event }) => ({
      id: event.id,
      name: `${shortRiver(river)} ${event.date} · CoV ${formatNumber(event.cov_percent, 0)}%`,
      value: event.scores.nse, display: formatNumber(event.scores.nse, 2),
    })), current.id);
  divergingBars(document.getElementById("val-bias"),
    events.map(({ river, event }) => ({
      id: event.id,
      name: `${shortRiver(river)} ${event.date}`,
      value: event.scores.percent_bias, display: `${formatNumber(event.scores.percent_bias, 1)}%`,
    })), current.id);
}

function renderDiagnosis(event) {
  document.getElementById("diagnosis-note").textContent = state.data.diagnostics_note.text;
  const d = event.diagnostics || {};
  const tiles = [];
  if (d.volume_ratio != null) {
    tiles.push({ k: "Volume delivered", v: `${formatNumber(d.volume_ratio * 100, 0)}%`,
      s: "of the observed total — a level error" });
  }
  if (d.amplitude_ratio != null) {
    tiles.push({ k: "Swing reproduced", v: `${formatNumber(d.amplitude_ratio * 100, 0)}%`,
      s: "of the observed rise-and-fall — a shape error" });
  }
  if (d.routing_lag_error_min != null && d.modeled_routing_lag_min != null) {
    const fast = d.routing_lag_error_min < 0;
    tiles.push({ k: "Routing time", v: `${fast ? "−" : "+"}${formatNumber(Math.abs(d.routing_lag_error_min), 0)} min`,
      s: `modelled ${formatNumber(d.modeled_routing_lag_min, 0)} vs observed ${formatNumber(d.observed_routing_lag_min, 0)} min — routes too ${fast ? "fast" : "slow"}` });
  } else if (d.peak_lag_min != null) {
    tiles.push({ k: "Peak timing", v: `${formatNumber(d.peak_lag_min, 0)} min`,
      s: "modelled peak vs observed" });
  }
  if (d.unexplained_volume_fraction != null) {
    tiles.push({ k: "Unexplained volume", v: `${formatNumber(d.unexplained_volume_fraction * 100, 0)}%`,
      s: "of downstream flow — see guard below" });
  }
  const grid = document.getElementById("diagnosis-grid");
  grid.innerHTML = tiles.map((t) =>
    `<div class="diag"><span class="diag-k"></span><span class="diag-v mono"></span><span class="diag-s"></span></div>`).join("");
  grid.querySelectorAll(".diag").forEach((node, i) => {
    node.querySelector(".diag-k").textContent = tiles[i].k;
    node.querySelector(".diag-v").textContent = tiles[i].v;
    node.querySelector(".diag-s").textContent = tiles[i].s;
  });

  const card = document.getElementById("counterfactual-card");
  const cf = d.volume_only_counterfactual;
  if (cf && cf.scaled_nse != null) {
    card.hidden = false;
    card.innerHTML =
      `<strong>Volume-only counterfactual.</strong> If the prediction were rescaled by
       ×${formatNumber(cf.scale, 3)} to match the observed total volume, Nash–Sutcliffe would be
       <b>${formatNumber(cf.scaled_nse, 2)}</b> instead of ${formatNumber(event.scores.nse, 2)} —
       so most of the shortfall is a level error, not a timing one.
       <span class="guard">${cf.guard || ""}</span>`;
  } else {
    card.hidden = true;
  }
}

function renderTerrain(event) {
  const t = event.terrain || {};
  const rows = [
    ["Solver", "Saint-Venant 2-D"],
    ["Terrain", t.name ? `${t.name}${t.x_cells ? ` — ${t.x_cells}×${t.y_cells} cells` : ""}` : "—"],
    ["Status", humanStatus(event.status)],
    ["Readings compared", `${event.scores.n}`],
  ];
  const grid = document.getElementById("terrain-grid");
  grid.innerHTML = rows.map(() =>
    `<div class="param"><span class="param-k"></span><span class="param-v mono"></span></div>`).join("")
    + (t.limitation ? `<div class="param param-wide"><span class="param-k">Limitation</span><span class="param-v"></span></div>` : "");
  const cells = grid.querySelectorAll(".param");
  rows.forEach((r, i) => {
    cells[i].querySelector(".param-k").textContent = r[0];
    cells[i].querySelector(".param-v").textContent = r[1];
  });
  if (t.limitation) cells[cells.length - 1].querySelector(".param-v").textContent = t.limitation;
}

function renderLimits(river) {
  const limits = document.getElementById("val-limits");
  const common = [
    "This is an uncalibrated 2-D screening, not a certification. Nothing is tuned to the gauge, and the model is not corrected for the biases shown.",
    "Nash–Sutcliffe is unreliable when the observed flow barely varies; read it next to each event's variability (CoV).",
    "Each reach is a declared 2-D terrain (a laterally-uniform “ribbon” for these cases), not surveyed floodplain topography.",
    "The volume and routing diagnostics combine intervening tributaries, withdrawals, and reach storage; they are diagnostic, not a measured lateral flow.",
  ];
  const perRiver = {
    colorado: "Four days on one regulated reach test transfer across seasons, not across geography.",
    truckee: "Two flashy events on a small river — where the flow really moves, the fit is strong (NSE up to 0.96).",
    rio_grande: "A single predeclared third-river test: fit nothing, run once, keep the result. Near-steady flow makes NSE uninformative, so judge it on the ~5% magnitude match.",
    russian: "A large under-prediction (bias −76%): the downstream gauge saw far more water than routing the upstream gauge alone explains — likely intervening inflow this reach model omits.",
  };
  limits.innerHTML = "<strong>How to read this</strong><ul></ul>";
  const list = limits.querySelector("ul");
  for (const item of [...common, perRiver[river.id]].filter(Boolean)) {
    const li = document.createElement("li");
    li.textContent = item;
    list.appendChild(li);
  }
}

export async function initValidation() {
  try {
    const response = await fetch("data/validation.json");
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    state.data = await response.json();
    renderMetricNote();
    renderRiverChoice();
    selectRiver(state.data.rivers[0]);
  } catch (error) {
    showError(`Could not load the validation results (${error.message}). Serve this folder over HTTP: python -m http.server`);
  }
}
