/* Validation tab: the model run against real observed events, across rivers.
 *
 * Source data: website/data/validation.json, generated by
 * `python website/build_scenarios.py --validation` from the tracked outputs of
 * src/rivers/validation/{run_suite,calibrate_suite}.py. Nothing here recomputes
 * anything from the solver.
 *
 * Deliberate framing: this is an *uncalibrated comparison*, not a certification.
 * Two honesty devices run throughout:
 *   - Every Nash-Sutcliffe score is shown next to the event's observed
 *     variability (CoV). NSE's denominator is the observed variance, so on a
 *     nearly-steady river it turns unreliable; the page says so rather than
 *     letting a scary negative number stand unexplained.
 *   - Where the model is calibrated, the parameters' identifiability warning is
 *     shown next to the improved scores, so calibrated is never read as validated.
 */

import {
  divergingBars,
  formatNumber,
  multiSeriesChart,
  scatterChart,
} from "./charts.js";

const STATUS = {
  uncalibrated_baseline: "baseline",
  out_of_sample_validation: "out-of-sample",
  predeclared_third_river_transfer_test: "predeclared transfer test",
};

const state = { data: null, river: null, event: null };

function showError(message) {
  const card = document.getElementById("validation-error");
  card.hidden = false;
  card.textContent = message;
}

function statusLabel(id) {
  return STATUS[id] || String(id).replace(/_/g, " ");
}

/** Flatten every event across every river, for the global skill/bias bars. */
function allEvents() {
  return state.data.rivers.flatMap((river) =>
    river.events.map((event) => ({ river, event })));
}

function shortRiver(river) {
  return river.name.split("—")[0].trim().replace(" River", "");
}

function renderMetricNote() {
  const note = state.data.metric_note;
  const host = document.getElementById("metric-note");
  host.innerHTML = `<strong></strong><p></p>`;
  host.querySelector("strong").textContent = note.title;
  host.querySelector("p").textContent = note.text;
}

function renderRiverChoice() {
  const host = document.getElementById("river-choice");
  host.innerHTML = "";
  for (const river of state.data.rivers) {
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `<span class="name"></span>
      <span class="meta"><span class="chip-status"></span><span class="chip-score mono"></span></span>`;
    button.querySelector(".name").textContent = shortRiver(river);
    const chip = button.querySelector(".chip-status");
    chip.textContent = river.kind === "predeclared_transfer_test" ? "predeclared test"
      : river.kind === "fixed_parameter_suite" ? "fixed-parameter suite" : "independent river";
    chip.classList.add(river.kind === "fixed_parameter_suite" ? "base" : "oos");
    button.querySelector(".chip-score").textContent =
      `${river.events.length} event${river.events.length > 1 ? "s" : ""}`;
    button.onclick = () => selectRiver(river);
    host.appendChild(button);
  }
}

function selectRiver(river) {
  state.river = river;
  document.querySelectorAll("#river-choice button").forEach((b, i) =>
    b.setAttribute("aria-pressed", state.data.rivers[i] === river ? "true" : "false"));

  const host = document.getElementById("event-choice-val");
  host.innerHTML = "";
  for (const event of river.events) {
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `<span class="name"></span>
      <span class="meta"><span class="chip-score mono"></span><span class="chip-cov mono"></span></span>`;
    button.querySelector(".name").textContent = event.date;
    button.querySelector(".chip-score").textContent = `NSE ${formatNumber(event.scores.nse, 2)}`;
    const cov = button.querySelector(".chip-cov");
    cov.textContent = `CoV ${formatNumber(event.cov_percent, 0)}%`;
    if (event.low_variability) cov.classList.add("low");
    button.onclick = () => selectEvent(river, event);
    host.appendChild(button);
  }

  renderCalibration(river);
  renderResidual(river);
  renderParameters(river);
  renderLimits(river);
  selectEvent(river, river.events[0]);
}

function selectEvent(river, event) {
  state.event = event;
  document.querySelectorAll("#event-choice-val button").forEach((b, i) =>
    b.setAttribute("aria-pressed", river.events[i] === event ? "true" : "false"));

  document.getElementById("case-purpose").textContent =
    `${event.name} — ${statusLabel(event.status)}.` + (event.purpose ? ` ${event.purpose}` : "");

  // Predeclared registration note (Rio Grande): the pre-registration is the
  // strongest thing about that experiment, so it is surfaced, not buried.
  const preNote = document.getElementById("predeclared-note");
  if (event.predeclared && river.predeclared_policy) {
    const policy = river.predeclared_policy;
    preNote.hidden = false;
    preNote.innerHTML =
      `<div class="policy-head"><h2>Predeclared before any data was seen</h2></div>
       <p class="policy-line">${policy.event_basis || ""} ${policy.first_run_policy || ""}</p>`;
  } else {
    preNote.hidden = true;
  }

  renderReadouts(event);

  document.getElementById("val-hydro-title").textContent =
    `Modelled against observed discharge — ${shortRiver(river)}, ${event.date}`;
  multiSeriesChart(document.getElementById("val-hydrograph"), {
    times: event.times_min,
    unit: "discharge (m³/min)",
    series: [
      { label: "observed at the gauge", values: event.observed_m3_per_min, color: "#0b7285", width: 2.2 },
      { label: "modelled", values: event.predicted_m3_per_min, color: "#c0392b", width: 2, dash: "6 4" },
    ],
  });
  scatterChart(document.getElementById("val-scatter"), {
    observed: event.observed_m3_per_min,
    predicted: event.predicted_m3_per_min,
    unit: "(m³/min)",
  });
  renderReadAcross(event);
  renderSkillBars(event);
}

function renderReadouts(event) {
  const s = event.scores;
  const nseSub = event.low_variability
    ? `unreliable here — flow varied only ${formatNumber(event.cov_percent, 1)}%`
    : s.nse < 0 ? "worse than predicting the mean" : "1 perfect · 0 = the mean · <0 worse";
  document.getElementById("case-scores").innerHTML = [
    { k: "Nash–Sutcliffe", v: formatNumber(s.nse, 2), sub: nseSub, warn: event.low_variability },
    { k: "Observed variability", v: `${formatNumber(event.cov_percent, 1)}%`,
      sub: event.low_variability ? "nearly steady — prefer r and bias" : "coefficient of variation" },
    { k: "Correlation", v: formatNumber(s.pearson_r, 3), sub: "how well the shape matches" },
    { k: "Bias", v: `${formatNumber(s.percent_bias, 1)}%`,
      sub: `${formatNumber(Math.abs(s.bias), 0)} m³/min too ${s.bias < 0 ? "little" : "much"}` },
  ].map((r) => `<div class="readout${r.warn ? " warn" : ""}"><span class="k">${r.k}</span>` +
    `<span class="v">${r.v}</span><span class="s">${r.sub}</span></div>`).join("");
}

function renderReadAcross(event) {
  const s = event.scores;
  const host = document.getElementById("val-readacross");
  if (event.low_variability) {
    host.innerHTML =
      `<h3>What that shows</h3>
       <p class="readacross-line">This day's flow barely moved — it varied only
       <b>${formatNumber(event.cov_percent, 1)}%</b> around its mean. The model reproduces that
       near-constant level to within <b>${formatNumber(Math.abs(s.percent_bias), 1)}%</b>
       (correlation ${formatNumber(s.pearson_r, 2)}).</p>
       <p class="readacross-line">The Nash–Sutcliffe score of <b>${formatNumber(s.nse, 2)}</b> looks
       alarming only because NSE divides by the observed variance, which is tiny here. On a nearly
       steady river it is the wrong lens; the ~${formatNumber(Math.abs(s.percent_bias), 0)}% magnitude
       match is the honest read.</p>`;
    return;
  }
  const below = event.observed_m3_per_min.filter((o, i) => event.predicted_m3_per_min[i] < o).length;
  const belowShare = (below / event.observed_m3_per_min.length) * 100;
  const over = s.percent_bias > 0;
  const onSide = over ? 100 - belowShare : belowShare;
  host.innerHTML =
    `<h3>What that shows</h3>
     <p class="readacross-line">The model tracks the <b>shape</b> of the day well —
     correlation ${formatNumber(s.pearson_r, 3)} — but runs <b>${over ? "above" : "below"}</b> the gauge
     by <b>${formatNumber(Math.abs(s.percent_bias), 1)}%</b> on average
     (${formatNumber(onSide, 0)}% of the ${s.n} readings on that side).</p>
     <p class="readacross-line">An offset that holds across independent events points at the reach
     description — roughness, width, and slope are estimates and the channel is treated as one
     uniform reach — rather than at the numerics.</p>`;
}

function renderSkillBars(current) {
  const events = allEvents();
  divergingBars(document.getElementById("val-skill"),
    events.map(({ river, event }) => ({
      id: event.id,
      name: `${shortRiver(river)} ${event.date} · CoV ${formatNumber(event.cov_percent, 0)}%`,
      value: event.scores.nse, display: formatNumber(event.scores.nse, 2),
    })), current.id);
  divergingBars(document.getElementById("val-bias"),
    events.map(({ river, event }) => ({
      id: event.id,
      name: `${shortRiver(river)} ${event.date}`,
      value: event.scores.percent_bias, display: `${formatNumber(event.scores.percent_bias, 1)}%`,
    })), current.id);
}

function renderCalibration(river) {
  const block = document.getElementById("calibration-block");
  if (!river.calibration) { block.hidden = true; return; }
  block.hidden = false;
  const cal = river.calibration;
  const order = ["training", "validation", "test"];
  const labels = { training: "Training", validation: "Validation (held out)", test: "Test (held out)" };
  const rows = order.filter((k) => cal.splits[k]).map((k) => {
    const s = cal.splits[k];
    const delta = s.calibrated_nse - s.baseline_nse;
    return `<div class="cal-row">
      <span class="cal-split">${labels[k]}</span>
      <span class="cal-cell"><span class="cal-lab">NSE</span>
        <span class="mono">${formatNumber(s.baseline_nse, 2)} → <b>${formatNumber(s.calibrated_nse, 2)}</b></span></span>
      <span class="cal-cell"><span class="cal-lab">|bias|</span>
        <span class="mono">${formatNumber(s.baseline_abs_pct_bias, 1)}% → <b>${formatNumber(s.calibrated_abs_pct_bias, 1)}%</b></span></span>
      <span class="cal-delta ${delta >= 0 ? "up" : "down"} mono">${delta >= 0 ? "+" : ""}${formatNumber(delta, 2)}</span>
    </div>`;
  }).join("");
  document.getElementById("cal-splits").innerHTML =
    `<div class="cal-head"><span>split</span><span>Nash–Sutcliffe</span><span>bias</span><span>ΔNSE</span></div>${rows}`;

  const p = cal.selected_parameters;
  const hits = Object.keys(cal.identifiability.boundary_hits || {});
  document.getElementById("cal-identifiability").innerHTML =
    `<strong>Calibrated, not validated.</strong> The fit scales roughness ×${formatNumber(p.manning_scale, 2)},
     width ×${formatNumber(p.width_scale, 2)}, slope ×${formatNumber(p.slope_scale, 2)}, and adds a
     ${formatNumber(p.lateral_inflow_fraction * 100, 1)}% lateral gain. Held-out NSE improves — but
     ${hits.length ? `<b>${hits.map((h) => h.replace("_scale", "")).join(", ")}</b> all land at the edge
     of the tested range, so the fit is not uniquely identified: these are effective knobs that
     compensate for one another, not measured river properties.`
     : "the parameters are within the tested range."}`;
}

function renderResidual(river) {
  const block = document.getElementById("residual-block");
  const finding = state.data.residual_finding;
  // The residual finding is a Colorado diagnosis; show it only there.
  if (river.id !== "colorado" || !finding) { block.hidden = true; return; }
  block.hidden = false;
  document.getElementById("residual-title").textContent = finding.title;
  document.getElementById("residual-text").textContent = finding.text;

  const rows = finding.per_event;
  const scale = Math.max(...rows.flatMap((r) => [r.early, r.middle, r.late].map(Math.abs)), 1);
  const bar = (value) => {
    const width = Math.max((Math.abs(value) / scale) * 100, 1.5);
    return `<span class="rt-track"><span class="rt-fill ${value < 0 ? "neg" : ""}" style="width:${width}%"></span></span>
      <span class="rt-val mono">${formatNumber(value, 0)}</span>`;
  };
  document.getElementById("residual-bars").innerHTML =
    `<div class="rt-head"><span>event</span><span>early third</span><span>middle</span><span>late third</span></div>` +
    rows.map((r) =>
      `<div class="rt-row"><span class="rt-date mono">${r.date}</span>
        <span class="rt-cell">${bar(r.early)}</span>
        <span class="rt-cell">${bar(r.middle)}</span>
        <span class="rt-cell">${bar(r.late)}</span></div>`).join("") +
    `<p class="rt-foot">Residual = observed − modelled (m³/min). Positive means the model ran low.</p>`;
}

function renderParameters(river) {
  const block = document.getElementById("params-block");
  const p = river.fixed_parameters;
  if (!p) { block.hidden = true; return; }
  block.hidden = false;
  document.getElementById("params-note").textContent =
    river.parameter_policy || "Held identical across every event of this river.";
  const rows = [
    ["Reach length", `${formatNumber(p.length_m / 1000, 2)} km`],
    ["Grid cells", `${p.cells}`],
    ["Bed slope", `${p.slope}`],
    ["Manning n", `${formatNumber(p.manning_n, 6)}${river.roughness_origin ? ` — ${river.roughness_origin}` : ""}`],
    ["Channel width", `${formatNumber(p.upstream_width_m, 0)} m, uniform`],
    ["Warm-up", p.warmup_min != null ? `${formatNumber(p.warmup_min / 60, 0)} h, observed hydrograph` : "observed hydrograph"],
    ["Lateral inflow", p.lateral_inflow != null ? String(p.lateral_inflow) : "none"],
    ["Rainfall", p.rainfall != null ? String(p.rainfall) : "none"],
  ];
  document.getElementById("val-params").innerHTML = rows.map(() =>
    `<div class="param"><span class="param-k"></span><span class="param-v mono"></span></div>`).join("");
  document.querySelectorAll("#val-params .param").forEach((node, i) => {
    node.querySelector(".param-k").textContent = rows[i][0];
    node.querySelector(".param-v").textContent = rows[i][1];
  });
}

function renderLimits(river) {
  const limits = document.getElementById("val-limits");
  const common = [
    "This is an uncalibrated comparison unless a calibration panel says otherwise, and even then the model is not corrected for the biases shown.",
    "Nash–Sutcliffe is unreliable when the observed flow barely varies; read it next to each event's variability (CoV).",
    "Every reach is a single uniform channel of estimated width, slope, and roughness — real rivers are none of those things.",
  ];
  const perRiver = {
    colorado: "Four days on this one regulated reach test transfer across seasons, not across geography.",
    truckee: "Two flashy snowmelt/rain events on a small river — where the flow really moves, the fit is strong (NSE up to 0.97).",
    rio_grande: "A single predeclared third-river test: fit nothing, run once, keep the result. The near-steady flow makes NSE uninformative, so judge it on the ~5% magnitude match.",
  };
  limits.innerHTML = "<strong>How to read this</strong><ul></ul>";
  const list = limits.querySelector("ul");
  for (const item of [...common, perRiver[river.id]].filter(Boolean)) {
    const li = document.createElement("li");
    li.textContent = item;
    list.appendChild(li);
  }
}

export async function initValidation() {
  try {
    const response = await fetch("data/validation.json");
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    state.data = await response.json();
    renderMetricNote();
    renderRiverChoice();
    selectRiver(state.data.rivers[0]);
  } catch (error) {
    showError(`Could not load the validation results (${error.message}). Serve this folder over HTTP: python -m http.server`);
  }
}
