/* Validation tab: the model run against real observed events.
 *
 * Source data: website/data/validation.json, generated by
 * `python website/build_scenarios.py --validation` from the outputs of
 * src/rivers/validation/run_suite.py. Nothing here recomputes anything.
 *
 * Framing note, deliberate: this suite is an *uncalibrated comparison*, not a
 * pass. One case is a baseline and three are out-of-sample; one of those has a
 * negative Nash-Sutcliffe score. The page says so rather than implying the
 * model is "validated".
 */

import {
  divergingBars,
  formatNumber,
  multiSeriesChart,
  scatterChart,
} from "./charts.js";

const STATUS = {
  uncalibrated_baseline: {
    label: "baseline",
    blurb: "The event the reach parameters were first estimated against — not an independent test.",
  },
  out_of_sample_validation: {
    label: "out-of-sample",
    blurb: "An independent event: the model saw none of this day's downstream data.",
  },
};

const state = { data: null, current: null };

function showError(message) {
  const card = document.getElementById("validation-error");
  card.hidden = false;
  card.textContent = message;
}

function statusOf(id) {
  return STATUS[id] || { label: id, blurb: "" };
}

function renderPolicy() {
  const { suite, parameter_policy: policy, score_summary: summary, cases } = state.data;
  const outOfSample = cases.filter((c) => c.status === "out_of_sample_validation").length;
  const worst = summary.percent_bias.minimum;
  const best = summary.percent_bias.maximum;
  document.getElementById("policy-card").innerHTML = `
    <div class="policy-head">
      <h2></h2>
      <span class="mono policy-gauges"></span>
    </div>
    <p class="policy-line"></p>
    <div class="policy-stats">
      <span><b>${cases.length}</b> events · <b>${outOfSample}</b> out-of-sample</span>
      <span>Nash–Sutcliffe <b>${formatNumber(summary.nse.minimum, 2)}</b> to
        <b>${formatNumber(summary.nse.maximum, 2)}</b></span>
      <span>bias <b>${formatNumber(best, 1)}%</b> to <b>${formatNumber(worst, 1)}%</b>,
        under-predicting on every event</span>
    </div>`;
  document.getElementById("policy-card").querySelector("h2").textContent = suite.name;
  document.getElementById("policy-card").querySelector(".policy-gauges").textContent =
    `${suite.upstream_gauge} → ${suite.downstream_gauge}`;
  document.getElementById("policy-card").querySelector(".policy-line").textContent = policy;
}

function renderCaseList() {
  const host = document.getElementById("case-choice");
  host.innerHTML = "";
  for (const c of state.data.cases) {
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `<span class="name"></span>
      <span class="meta"><span class="chip-status"></span><span class="chip-score"></span></span>`;
    button.querySelector(".name").textContent = c.date;
    const status = statusOf(c.status);
    const chip = button.querySelector(".chip-status");
    chip.textContent = status.label;
    chip.classList.add(c.status === "out_of_sample_validation" ? "oos" : "base");
    button.querySelector(".chip-score").textContent = `NSE ${formatNumber(c.scores.nse, 2)}`;
    button.onclick = () => selectCase(c);
    host.appendChild(button);
  }
}

function selectCase(c) {
  state.current = c;
  document.querySelectorAll("#case-choice button").forEach((b, i) =>
    b.setAttribute("aria-pressed", state.data.cases[i] === c ? "true" : "false"));

  const status = statusOf(c.status);
  document.getElementById("case-purpose").textContent = `${c.name} — ${status.blurb}`;

  const s = c.scores;
  document.getElementById("case-scores").innerHTML = [
    { k: "Nash–Sutcliffe", v: formatNumber(s.nse, 3),
      sub: s.nse < 0 ? "worse than predicting the mean" : "1 = perfect, 0 = no better than the mean" },
    { k: "Bias", v: `${formatNumber(s.percent_bias, 1)}%`,
      sub: `${formatNumber(Math.abs(s.bias), 0)} m³/min too ${s.bias < 0 ? "little" : "much"}, on average` },
    { k: "Correlation", v: formatNumber(s.pearson_r, 3), sub: "how well the shape matches" },
    { k: "RMSE", v: formatNumber(s.rmse, 0), sub: `m³/min across ${s.n} readings` },
  ].map((r) => `<div class="readout"><span class="k">${r.k}</span>` +
    `<span class="v">${r.v}</span><span class="s">${r.sub}</span></div>`).join("");

  document.getElementById("val-hydro-title").textContent =
    `Modelled against observed discharge — ${c.date}`;
  multiSeriesChart(document.getElementById("val-hydrograph"), {
    times: c.times_min,
    unit: "discharge (m³/min)",
    series: [
      { label: "observed at the gauge", values: c.observed_m3_per_min, color: "#0b7285", width: 2.2 },
      { label: "modelled", values: c.predicted_m3_per_min, color: "#c0392b", width: 2, dash: "6 4" },
    ],
  });

  scatterChart(document.getElementById("val-scatter"), {
    observed: c.observed_m3_per_min,
    predicted: c.predicted_m3_per_min,
    unit: "(m³/min)",
  });

  // Plain-language read of what the scatter shows, computed rather than asserted.
  const below = c.observed_m3_per_min.filter((o, i) => c.predicted_m3_per_min[i] < o).length;
  const share = (below / c.observed_m3_per_min.length) * 100;
  document.getElementById("val-readacross").innerHTML =
    `<h3>What that shows</h3>
     <p class="readacross-line">The model tracks the <b>shape</b> of the day well —
     correlation ${formatNumber(c.scores.pearson_r, 2)} — but sits <b>below</b> the gauge in
     ${formatNumber(share, 0)}% of the ${c.scores.n} readings, by
     ${formatNumber(Math.abs(c.scores.percent_bias), 1)}% on average.</p>
     <p class="readacross-line">A consistent offset like this across four independent events points
     at the reach description rather than at the numerics: roughness, width, and slope here are
     estimates, and the reach is treated as a single uniform channel with no lateral inflow.</p>`;

  divergingBars(document.getElementById("val-skill"),
    state.data.cases.map((row) => ({
      id: row.id, name: `${row.date} · ${statusOf(row.status).label}`,
      value: row.scores.nse, display: formatNumber(row.scores.nse, 2),
    })), c.id);
  divergingBars(document.getElementById("val-bias"),
    state.data.cases.map((row) => ({
      id: row.id, name: `${row.date} · ${statusOf(row.status).label}`,
      value: row.scores.percent_bias, display: `${formatNumber(row.scores.percent_bias, 1)}%`,
    })), c.id);
}

function renderParameters() {
  const p = state.data.fixed_parameters;
  const rows = [
    ["Reach length", `${formatNumber(p.length_m / 1000, 2)} km`],
    ["Grid cells", `${p.cells}`],
    ["Bed slope", `${p.slope}`],
    ["Manning n", `${formatNumber(p.manning_n, 6)} (${state.data.roughness_origin})`],
    ["Channel width", `${formatNumber(p.upstream_width_m, 0)} m, uniform`],
    ["Warm-up", `${formatNumber(p.warmup_min / 60, 0)} h`],
    ["Lateral inflow", p.lateral_inflow],
    ["Rainfall", p.rainfall],
    ["Initial condition", p.initial_condition],
  ];
  document.getElementById("val-params").innerHTML = rows.map(([k, v]) =>
    `<div class="param"><span class="param-k"></span><span class="param-v mono"></span></div>`)
    .join("");
  document.querySelectorAll("#val-params .param").forEach((node, i) => {
    node.querySelector(".param-k").textContent = rows[i][0];
    node.querySelector(".param-v").textContent = rows[i][1];
  });

  const limits = document.getElementById("val-limits");
  limits.innerHTML = "<strong>How to read this</strong><ul></ul>";
  const list = limits.querySelector("ul");
  for (const item of [
    "This is an uncalibrated comparison, not a certification. Nothing here was tuned to make the model match, and the model has not been corrected for the bias these events reveal.",
    "One of the four events scores below zero on Nash–Sutcliffe, meaning the model did worse on that day than simply predicting the average flow.",
    "The reach is represented as a single uniform channel of estimated width, slope, and roughness, with no tributary inflow and no rain — a real 25 km of the Colorado is none of those things.",
    "Four days on one river is a narrow evidence base. It supports statements about this reach and these conditions, and nothing broader.",
  ]) {
    const li = document.createElement("li");
    li.textContent = item;
    list.appendChild(li);
  }
}

export async function initValidation() {
  try {
    const response = await fetch("data/validation.json");
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    state.data = await response.json();
    renderPolicy();
    renderCaseList();
    renderParameters();
    selectCase(state.data.cases[0]);
  } catch (error) {
    showError(`Could not load the validation results (${error.message}). Serve this folder over HTTP: python -m http.server`);
  }
}
